### ISSUE TITLE
Issue with 0.9.9+2 package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/glm#1]
A couple of minor issues I've noted:

1. In `gml/buildfile` you have `hxx{**...h}` -- I believe `hxx{**.h}` will do just as well and is more canonical/unsurprising.

2. In `gml/buildfile` there is no need to set `cxx.poptions` since this is a header-only library.

**Comment by lyrahgames** [comment]
>     1. In `gml/buildfile` you have `hxx{**...h}` -- I believe `hxx{**.h}` will do just as well and is more canonical/unsurprising.

Thanks for the clarification. It seems that I have completely misunderstood the extension operator. After reading the manual, again, I could also use it to simplify another package.

>     2. In `gml/buildfile` there is no need to set `cxx.poptions` since this is a header-only library.

Actually, I thought so, but in [this issue](https://github.com/build2-packaging/stb/issues/4) of the `stb` libraries I didn't really understand why we need to add `c.libs = -lm` for a header-only build when using the `liba{}` target. So, I wanted to make sure, I wouldn't forget anything and also added the `cxx.poptions`.

**Comment by boris-kolpackov** [comment]
> Actually, I thought so, but in https://github.com/build2-packaging/stb/issues/4 of the stb libraries I didn't really understand why we need to add `c.libs = -lm` for a header-only build when using the `liba{}` target.

Ok, I've finally found time to write something up on this:

https://github.com/build2/HOWTO/blob/master/entries/make-header-only-library.md

For background, see:

https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#intro-lib

**Comment by lyrahgames** [comment]
Thank you for writing something up. That is really helpful!
